platform :ios, :deployment_target => '6.0'

pod 'TestFlightSDK'

link_with ['Testable']

target :spec, :exclusive => true do
    pod 'Kiwi'
    pod 'OCHamcrest'
    pod 'Sealant'
    pod 'Sealant/Kiwi'
    pod 'Sealant/MKNetworkKit'
    pod 'Sealant/TestFlight'
    pod 'Sealant/Objection'
    link_with ['App Specs', 'Unit Specs']
end

target :integration do
    pod 'KIF'
    link_with 'Integration Tests'
end
